
insert into category(name, newest, home, parent) values ('Thiết kế kiến trúc', TRUE, FALSE, 0)
insert into category(name, newest, home, parent) values ('Thi công xây dựng', TRUE, FALSE, 0)
insert into category(name, newest, home, parent) values ('Thi công chống thấm', TRUE, FALSE, 0)
insert into category(name, newest, home, parent) values ('Tư vấn giám sát, quản lý', TRUE, FALSE, 0)
insert into category(name, newest, home, parent) values ('Cải tạo, sửa chửa', TRUE, FALSE, 0)
insert into category(name, newest, home, parent) values ('Tin tức', FALSE, FALSE, 0)

insert into category(name, newest, home, parent) values ('Quy trình thiết kế kiến trúc', TRUE, FALSE, 1)
insert into category(name, newest, home, parent) values ('Thiết kế nhà phố', TRUE, FALSE, 1)
insert into category(name, newest, home, parent) values ('Biệt thự', TRUE, FALSE, 1)
insert into category(name, newest, home, parent) values ('Đơn giá thiết kế kiến trúc', TRUE, FALSE, 1)

insert into category(name, newest, home, parent) values ('Quy trình thi công xây dựng', TRUE, FALSE, 2)
insert into category(name, newest, home, parent) values ('Xây dựng nhà phố', TRUE, FALSE, 2)
insert into category(name, newest, home, parent) values ('Xây dựng biệt thự', TRUE, FALSE, 2)
insert into category(name, newest, home, parent) values ('Xây dựng nhà xưởng', TRUE, FALSE, 2)
insert into category(name, newest, home, parent) values ('Danh mục vật liệu xây dựng', TRUE, FALSE, 2)
insert into category(name, newest, home, parent) values ('Đơn giá thi công', TRUE, FALSE, 2)

insert into category(name, newest, home, parent) values ('Quy trình thi công chống thấm', TRUE, FALSE, 3)
insert into category(name, newest, home, parent) values ('Sàn mái, sân thượng', TRUE, FALSE, 3)
insert into category(name, newest, home, parent) values ('Tường tầng hầm, kết cấu hồ bơi, kết cấu bể nước', TRUE, FALSE, 3)
insert into category(name, newest, home, parent) values ('Sàn toilet, sàn ban công, sê nô', TRUE, FALSE, 3)
insert into category(name, newest, home, parent) values ('Đơn giá thi công chống thấm', TRUE, FALSE, 3)

insert into category(name, newest, home, parent) values ('Quy trình cải tạo, sửa chữa', TRUE, FALSE, 5)
insert into category(name, newest, home, parent) values ('Cải tạo, sửa chữa nhà phố', TRUE, FALSE, 5)
insert into category(name, newest, home, parent) values ('Cải tạo, sửa chữa biệt thự', TRUE, FALSE, 5)
insert into category(name, newest, home, parent) values ('Cải tạo, sửa chữa văn phòng', TRUE, FALSE, 5)
insert into category(name, newest, home, parent) values ('Chống thấm sàn toilet, sàn ban công, sê nô', TRUE, FALSE, 5)
insert into category(name, newest, home, parent) values ('Cải tạo, sửa chữa, mở rộng nhà xưởng', TRUE, FALSE, 5)

insert into category(name, newest, home, parent) values ('Tin khuyến mãi', FALSE, FALSE, 6)
insert into category(name, newest, home, parent) values ('Tin nhanh 24h', FALSE, FALSE, 6)
insert into category(name, newest, home, parent) values ('Tin chuyên ngành', FALSE, FALSE, 6)
insert into category(name, newest, home, parent) values ('Quy chuẩn, tiêu chuẩn xây dựng', FALSE, FALSE, 6)
